/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.plan.maps;

import java.awt.BorderLayout;
import org.geotools.swing.MapLayerTable;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.util.Lookup;

/**
 * Top component which displays something.
 */
@TopComponent.Description(preferredID = "LayerTableTopComponent",persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "rightSlidingSide", openAtStartup = true)
@TopComponent.OpenActionRegistration(displayName = "#CTL_LayerTableTopComponent",preferredID = "LayerTableTopComponent")
@ActionID(category = "Window", id = "org.plan.maps.LayerTableTopComponent")
@ActionReference(path = "Menu/Window")
public final class LayerTableTopComponent extends TopComponent {

    private MapLayerTable table;

    public LayerTableTopComponent() {
	initComponents();
	setName(NbBundle.getMessage(LayerTableTopComponent.class, "CTL_LayerTableTopComponent"));
	setToolTipText(NbBundle.getMessage(LayerTableTopComponent.class, "HINT_LayerTableTopComponent"));
	table = new MapLayerTable();
	table.setDoubleBuffered(true);
	SelectableMapImpl map = (SelectableMapImpl) Lookup.getDefault().lookup(MapProvider.class).getMainMap();
	table.setMapPane(map.getPane());
	add(table, BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
