/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.plan.maps;

import java.awt.BorderLayout;
import java.awt.Component;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.util.Lookup;
import org.openide.util.lookup.Lookups;

/**
 * Top component which displays something.
 */
@TopComponent.Description(preferredID = "MainMapTopComponent",persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MainMapTopComponent",preferredID = "MainMapTopComponent")
@ActionID(category = "Window", id = "org.plan.maps.MainMapTopComponent")
@ActionReference(path = "Menu/Window")
public final class MainMapTopComponent extends TopComponent {

    public MainMapTopComponent() {
	initComponents();
	setName(NbBundle.getMessage(MainMapTopComponent.class, "CTL_MainMapTopComponent"));
	setToolTipText(NbBundle.getMessage(MainMapTopComponent.class, "HINT_MainMapTopComponent"));
	putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);

	MapProvider mapProvider = Lookup.getDefault().lookup(MapProvider.class);
	SelectableMapImpl map = (SelectableMapImpl) mapProvider.getMainMap();
	add((Component) map, BorderLayout.CENTER);
	super.associateLookup(Lookups.proxy(map));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
